apiVersion: v1
kind: Service
metadata:
  name: tokenizer-service
  namespace: tokenizer
spec:
  type: NodePort
  selector:
    app: tokenizer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30181